export enum LayerTwoNetworks { // Added export keyword
    Optimism = "optimism",
    Arbitrum = "arbitrum",
    Polygon = "matic-network",
    ZkSync = "zksync",
    ImmutableX = "immutable-x",
    StarkNet = "starknet",
    BobaNetwork = "boba-network",
    Sushiswap = "sushi",
    Metis = "metis-token",
    HermezNetwork = "hermez-network-token",
    CelerNetwork = "celer-network",
    SynthetixSNXOnOptimism = "havven",
    Deversifi = "devve",
    Loopring = "loopring",
    Biconomy = "biconomy",
    BancorOnArbitrum = "bancor",
    AaveOnOptimism = "aave",
    PerpetualProtocol = "perpetual-protocol",
    Cartesi = "cartesi",
    Zora = "zora-bridged-weth-zora-network",
}