export enum LayerTwoNetworks { // Added export keyword
    Optimism = "Optimism",
    Arbitrum = "Arbitrum",
    Polygon = "Polygon",
    ZkSync = "ZkSync",
    ImmutableX = "Immutable X",
    StarkNet = "StarkNet",
    BobaNetwork = "Boba Network",
    Sushiswap = "Sushiswap",
    Metis = "Metis",
    HermezNetwork = "Hermez Network",
    CelerNetwork = "Celer Network",
    SynthetixSNXOnOptimism = "Synthetix (SNX) on Optimism",
    Deversifi = "Deversifi",
    Loopring = "Loopring",
    Biconomy = "Biconomy",
    BancorOnArbitrum = "Bancor on Arbitrum",
    AaveOnOptimism = "Aave on Optimism",
    PerpetualProtocol = "Perpetual Protocol",
    Cartesi = "Cartesi",
    Zora = "Zora",
}